-- Query 1: Find the total revenue generated by each vehicle category, including the number of rentals and average rental cost per category.
SELECT 
    vc.Name AS CategoryName,
    COUNT(r.RentalID) AS RentalCount,
    SUM(r.TotalCost) AS TotalRevenue,
    AVG(r.TotalCost) AS AverageRentalCost
FROM 
    Rental r
JOIN 
    Vehicle v ON r.VehicleID = v.VehicleID
JOIN 
    Vehicle_Category vc ON v.CategoryID = vc.CategoryID
GROUP BY 
    vc.Name;

-- Query 2: List all customers who have rented more than one vehicle, along with the total number of rentals and total cost.
SELECT 
    c.CustomerID,
    c.FirstName,
    c.LastName,
    COUNT(r.RentalID) AS TotalRentals,
    SUM(r.TotalCost) AS TotalCost
FROM 
    Customer c
JOIN 
    Rental r ON c.CustomerID = r.CustomerID
GROUP BY 
    c.CustomerID
HAVING 
    COUNT(r.RentalID) > 1;
    

-- Query 3: Find the top 5 most expensive rentals, including customer details, vehicle details, and insurance type.
SELECT 
    r.RentalID,
    c.FirstName,
    c.LastName,
    v.Brand,
    v.Model,
    i.Type AS InsuranceType,
    r.TotalCost
FROM 
    Rental r
JOIN 
    Customer c ON r.CustomerID = c.CustomerID
JOIN 
    Vehicle v ON r.VehicleID = v.VehicleID
LEFT JOIN 
    Rental_Insurance ri ON r.RentalID = ri.RentalID
LEFT JOIN 
    Insurance i ON ri.InsuranceID = i.InsuranceID
ORDER BY 
    r.TotalCost DESC
LIMIT 5;

-- Query 4: Find the top 5 most expensive rentals, including customer details, vehicle details, and insurance type.
SELECT 
    v.VehicleID,
    v.Brand,
    v.Model,
    COUNT(m.MaintenanceID) AS MaintenanceCount,
    SUM(m.Cost) AS TotalMaintenanceCost
FROM 
    Vehicle v
LEFT JOIN 
    Maintenance m ON v.VehicleID = m.VehicleID
GROUP BY 
    v.VehicleID;
    

-- Query 5: Find the average daily rate for each vehicle category, and compare it with the base daily rate.
SELECT 
    vc.Name AS CategoryName,
    vc.BaseDailyRate,
    AVG(v.DailyRate) AS AverageDailyRate
FROM 
    Vehicle v
JOIN 
    Vehicle_Category vc ON v.CategoryID = vc.CategoryID
GROUP BY 
    vc.Name, vc.BaseDailyRate;
    
    
-- Query 6: List all employees who have been with the company for more than 5 years, along with their role and location.
SELECT 
    e.EmployeeID,
    e.FirstName,
    e.LastName,
    e.Role,
    rl.Name AS LocationName,
    e.HireDate
FROM 
    Employee e
JOIN 
    Rental_Location rl ON e.LocationID = rl.LocationID
WHERE 
    e.HireDate <= DATE_SUB(CURDATE(), INTERVAL 5 YEAR);
    
-- Query 7: Find the total number of rentals, total revenue, and average rental duration (in days) for each rental location.
SELECT 
    rl.LocationID,
    rl.Name AS LocationName,
    COUNT(r.RentalID) AS TotalRentals,
    SUM(r.TotalCost) AS TotalRevenue,
    AVG(DATEDIFF(r.ReturnDate, r.PickupDate)) AS AverageRentalDuration
FROM 
    Rental r
JOIN 
    Employee e ON r.CustomerID = e.EmployeeID -- Assuming rentals are associated with employees
JOIN 
    Rental_Location rl ON e.LocationID = rl.LocationID
GROUP BY 
    rl.LocationID;
    
-- Group 58
-- Query to Analyze --
SELECT 
    vc.Name AS CategoryName,
    COUNT(r.RentalID) AS RentalCount,
    SUM(r.TotalCost) AS TotalRevenue,
    AVG(r.TotalCost) AS AverageRentalCost
FROM 
    Rental r
JOIN 
    Vehicle v ON r.VehicleID = v.VehicleID
JOIN 
    Vehicle_Category vc ON v.CategoryID = vc.CategoryID
GROUP BY 
    vc.Name;
